[fm95]
master_volume=1
stereo=1
calibration=0
agc_target=0.9
agc_attack=0.1
agc_release=0.5
agc_min=0.1
agc_max=3.5
bs412_attack=0.01
bs412_release=1
bs412_max=1.5
bs412_gate=-25
bs412_knee=8
bs412_strenght=3
rds_streams=1
mpx_power=2.85
[advanced]
lpf_order=16
preemp_unity=15000
lpf_cutoff=15000
headroom=0.2
stereo_ssb=0
drive=1.0
makeup=2.9
#sample_rate=384000
[devices]
input=FM_Audio.monitor
output=alsa_output.platform-soc_sound.pro-output-0
rds=RDS.monitor
mpx=FM_MPX.monitor
[volumes]
pilot=0.09
rds=0.055
rds_step=0.95
